/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f9f9ff',
        'surface-dim': '#d8d9e3',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f3fd',
        'surface-container': '#ecedf7',
        'surface-container-high': '#e6e7f2',
        'surface-container-highest': '#e1e2ec',
        'on-surface': '#191b23',
        'on-surface-variant': '#424754',
        'inverse-surface': '#2e3038',
        'inverse-on-surface': '#eff0fa',
        outline: '#727785',
        'outline-variant': '#c2c6d6',
        'surface-tint': '#005ac2',
        primary: '#0058be',
        'on-primary': '#ffffff',
        'primary-container': '#2170e4',
        'on-primary-container': '#fefcff',
        'inverse-primary': '#adc6ff',
        secondary: '#006c49',
        'on-secondary': '#ffffff',
        'secondary-container': '#6cf8bb',
        'on-secondary-container': '#00714d',
        tertiary: '#924700',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#b75b00',
        'on-tertiary-container': '#fffbff',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a42',
        'on-primary-fixed-variant': '#004395',
        'secondary-fixed': '#6ffbbe',
        'secondary-fixed-dim': '#4edea3',
        'on-secondary-fixed': '#002113',
        'on-secondary-fixed-variant': '#005236',
        'tertiary-fixed': '#ffdcc6',
        'tertiary-fixed-dim': '#ffb786',
        'on-tertiary-fixed': '#311400',
        'on-tertiary-fixed-variant': '#723600',
        background: '#f9f9ff',
        'on-background': '#191b23',
        'surface-variant': '#e1e2ec',
        mint: '#10B981',
        amber: '#F59E0B',
        red: '#EF4444',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
      },
      spacing: {
        'stack-sm': '4px',
        'stack-md': '12px',
        'stack-lg': '24px',
        gutter: '16px',
        base: '8px',
        'container-padding-mobile': '16px',
        'container-padding-desktop': '32px',
      },
      fontFamily: {
        'display-lg': ['Inter', 'sans-serif'],
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'body-lg': ['Outfit', 'sans-serif'],
        'body-md': ['Outfit', 'sans-serif'],
        'label-sm': ['Outfit', 'sans-serif'],
        'amount-lg': ['"JetBrains Mono"', 'monospace'],
        'amount-md': ['"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'amount-lg': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'amount-md': ['16px', { lineHeight: '24px', fontWeight: '500' }],
      },
      boxShadow: {
        'level-1': '0px 4px 12px rgba(30, 41, 59, 0.05)',
        'level-2': '0px 12px 24px rgba(30, 41, 59, 0.12)',
      },
      keyframes: {
        fadeIn: { '0%': { opacity: '0' }, '100%': { opacity: '1' } },
        fadeOut: { '0%': { opacity: '1' }, '100%': { opacity: '0' } },
        scaleIn: { '0%': { opacity: '0', transform: 'scale(0.95) translateY(4px)' }, '100%': { opacity: '1', transform: 'scale(1) translateY(0)' } },
        slideInRight: { '0%': { opacity: '0', transform: 'translateX(16px)' }, '100%': { opacity: '1', transform: 'translateX(0)' } },
        shimmer: { '0%': { backgroundPosition: '-400px 0' }, '100%': { backgroundPosition: '400px 0' } },
      },
      animation: {
        fadeIn: 'fadeIn 0.2s ease-out',
        fadeOut: 'fadeOut 0.2s ease-in',
        scaleIn: 'scaleIn 0.2s ease-out',
        slideInRight: 'slideInRight 0.25s ease-out',
        shimmer: 'shimmer 1.6s infinite linear',
      },
    },
  },
  plugins: [],
}
